CREATE DATABASE IF NOT EXISTS `my-economy`;
USE `my-economy`;

CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `SENHA` varchar(255) NOT NULL,
  `NOME` varchar(255) NOT NULL,
  `DT_NASCIMENTO` date NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `DESPESAS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(255) NOT NULL,
  `VALOR` decimal(10,2) NOT NULL,
  `MES` int NOT NULL,
  `ANO` int NOT NULL,
  `USUARIO_ID` int NOT NULL,
  `ICONE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`),
  CONSTRAINT `DESPESAS_ibfk_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `LIMITES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `VALOR` decimal(10,2) NOT NULL,
  `MES` int NOT NULL,
  `ANO` int NOT NULL,
  `USUARIO_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`),
  CONSTRAINT `LIMITES_ibfk_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 